version: '3.8'

services:
  backend:
    image: kaljmarik/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/cars
    depends_on:
      - db
    networks:
      - backbone

  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - backbone

  frontend:
    image: kaljmarik/frontend
    build:
      context: ./frontend  # Build from the frontend folder
      dockerfile: Dockerfile  # Use Dockerfile in the frontend folder
    ports:
      - "80:80"
    depends_on:
      - backend  # Ensure backend is started before frontend
    networks:
      - backbone  # Connect to the same network as other services

networks:
  backbone:
    driver: bridge
