version: '3.8'

services:
  backend:
    image: kaljmarik/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/cars
    depends_on:
      - db
    networks:
      - backbone

  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - backbone

  frontend:
    image: kaljmarik/frontend
    build:
      context: ./frontend  # Build from the frontend folder
      dockerfile: Dockerfile  # Use Dockerfile in the frontend folder
    depends_on:
      - backend  # Ensure backend is started before frontend
    networks:
      - backbone  # Connect to the same network as other services

  proxy:
    image: nginx:latest
    volumes:
      - ./frontend/build:/usr/share/nginx/html 
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # Mount the custom Nginx config
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - backend  # Ensure backend is started before Nginx
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
