apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: mongodb://mongo-service:27017/cars

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      upstream backend-service {
        server backend-service;
      }

      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html;
        }

        location /api/ {
          proxy_pass http://backend-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
