apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_API_URL: 'http://backend-service' # URL for backend service from frontend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: 'mongodb://mongo-service:27017/cars' # MongoDB connection string for backend
