stages:
  - build
  - deploy

build_backend:
  stage: build
  script:
    - docker build -t kaljmarik/backend:latest ./backend
    - docker push kaljmarik/backend:latest

build_frontend:
  stage: build
  script:
    - docker build -t kaljmarik/frontend:latest ./frontend
    - docker push kaljmarik/frontend:latest

deploy_k8s:
  stage: deploy
  script:
    - helm upgrade --install car-app ./helm -f values.yaml
  environment:
    name: production
