steps:
  # Step 1: Build and Push Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    dir: 'backend'
    args: ['build', '-t', 'eu.gcr.io/myreactapp-445621/backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', 'eu.gcr.io/myreactapp-445621/backend:latest']

  # Step 2: Build and Push Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    dir: 'frontend'
    args: ['build', '-t', 'eu.gcr.io/myreactapp-445621/frontend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args: ['push', 'eu.gcr.io/myreactapp-445621/frontend:latest']

  # Step 3: Set up kubectl with GKE credentials (Fixed with correct region)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Setup kubectl'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cluster-1' # Replace with your actual GKE cluster name
      - '--region'
      - 'europe-west1-b' # Use the correct region or subregion from your GKE setup
      - '--project'
      - 'myreactapp-445621' # Replace with your project ID

  # Step 4: Deploy with Helm
  - name: 'gcr.io/cloud-builders/helm'
    id: 'Helm Deploy'
    args:
      - 'upgrade'
      - '--install'
      - 'car-app'
      - './helm'
      - '-f'
      - 'values.yaml'
      - '--set'
      - 'backend.image=eu.gcr.io/myreactapp-445621/backend:latest'
      - '--set'
      - 'frontend.image=eu.gcr.io/myreactapp-445621/frontend:latest'

images:
  - 'eu.gcr.io/myreactapp-445621/backend:latest'
  - 'eu.gcr.io/myreactapp-445621/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
