steps:
  # Step 1: Build and Push Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    dir: 'backend'
    args: ['build', '-t', 'eu.gcr.io/myreactapp-445621/backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', 'eu.gcr.io/myreactapp-445621/backend:latest']

  # Step 2: Build and Push Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    dir: 'frontend'
    args: ['build', '-t', 'eu.gcr.io/myreactapp-445621/frontend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args: ['push', 'eu.gcr.io/myreactapp-445621/frontend:latest']

  # Step 3: Set up kubectl with GKE credentials (Fixed with correct region)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Setup kubectl'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cluster-1' # Replace with your actual GKE cluster name
      - '--region'
      - 'europe-west1-b' # Use the correct region or subregion from your GKE setup
      - '--project'
      - 'myreactapp-445621' # Replace with your project ID

  # Step 5: Helm Deploy
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Helm Deploy'
    dir: './Helm' # Ensures the script runs inside the Helm folder
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud components install gke-gcloud-auth-plugin
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

        gcloud container clusters get-credentials cluster-1 --zone europe-west1-b --project myreactapp-445621

        helm upgrade --install car-app . \
          -f values-prod.yaml \
          --set backend.image=eu.gcr.io/myreactapp-445621/backend:latest \
          --set frontend.image=eu.gcr.io/myreactapp-445621/frontend:latest

images:
  - 'eu.gcr.io/myreactapp-445621/backend:latest'
  - 'eu.gcr.io/myreactapp-445621/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
